# copyright.py - اطلاعات کپی رایت برنامه

from datetime import datetime

COPYRIGHT_TEXT = """
╔══════════════════════════════════════════════════════════════╗
║                                                              ║
║     Network Security Scanner v1.0                           ║
║     Created by: Payam Fekri                                 ║
║     License: Educational Purpose Only                       ║
║                                                              ║
║     "Security is not a product, but a process."             ║
║                                                              ║
╚══════════════════════════════════════════════════════════════╝
"""

BANNER = """
    ╔══════════════════════════════════════════════════════════════╗
    ║     🔒 Network Security Scanner v1.0                        ║
    ║     👨‍💻 Created by: Payam Fekri                              ║
    ║     📅 2024-2025                                            ║
    ║     🛡️ For authorized security testing only                 ║
    ╚══════════════════════════════════════════════════════════════╝
"""

def show_banner():
    """نمایش بنر در ابتدای برنامه"""
    from rich.console import Console
    from rich.panel import Panel
    
    console = Console()
    console.print(Panel(
        "[green]Network Security Scanner v5.0[/green]\n"
        "[cyan]Created by: Payam Fekri[/cyan]\n"
        "[yellow]For authorized security testing only[/yellow]",
        border_style="green"
    ))

def add_footer_to_pdf(pdf_story, pdf_styles):
    """اضافه کردن فوتر به PDF"""
    from reportlab.platypus import Paragraph, Spacer
    
    footer_text = f"Report generated by Network Security Scanner | Created by Payam Fekri | {datetime.now().strftime('%Y-%m-%d')}"
    pdf_story.append(Spacer(1, 30))
    pdf_story.append(Paragraph(footer_text, pdf_styles['MyNormal']))